#' Translate ODK relevant field
#'
#' \code{translate} converts conditions in ODK to R.
#'
#' @param relevant A string from ODK$relevant that needs to be translated.
#'
#' @param death A dataframe (one death) of ODK data.
#'
#' @details
#' This is a worker function.
#' 
#' @examples
#' \dontrun{
#' ## Example with 2016 WHO VA instrument version 1.5.1
#' record_f_name151 <- system.file("sample",
#'                                 "who151_odk_export.csv",
#'                                 package = "CrossVA")
#' records151 <- read.csv(record_f_name151, stringsAsFactors = FALSE)
#' 
#' form_f_name151 <- system.file("forms",
#'                               "WHOVA2016_v1_5_1_XLS_form_for_ODK_survey.csv",
#'                               package = "CrossVA")
#' form151 <- read.csv2(form_f_name151, stringsAsFactors = FALSE)
#' death <- records151[1,]
#' 
#' relevant <- form151$relevant[15]
#' translate(relevant, death)
#' }
#'
#' @importFrom stringi stri_replace_all_regex stri_count_words
#' @export
#'
translate <- function (relevant, death) {

    # parse field names
    splitNames <- strsplit(names(death), "\\.")
    fieldNames <- unlist(lapply(splitNames, function (x) x[length(x)]))
    names(death) <- fieldNames

    # remove \n
    patternSelected <- "\n"
    newRelevant <- stri_replace_all_regex(relevant, patternSelected, " ")

    # replace = with == (but not for >= or <= or !=)
    patternSelected <- "(?<![>|<|!])="
    newRelevant <- stri_replace_all_regex(newRelevant, patternSelected, "==")

    # translate selected() -- maybe have separate functions for these
    patternSelected <- "(?<!not\\()selected\\(\\$\\{([^\\}]+)\\}[^']+('[^']+')\\)"
    newRelevant <- stri_replace_all_regex(newRelevant, patternSelected, "death\\$$1 == $2")

    # translate not(selected())
    patternNotSelected <- "not\\(selected\\(\\$\\{([^\\}]+)\\}[^']+('[^']+')\\)\\)"
    newRelevant <- stri_replace_all_regex(newRelevant, patternNotSelected, "death\\$$1 != $2")

    # translate ${field_name} (separately for !=, =, >, and <)
    # \\1 = field name, \\2 = }, \\3 = relational operator/comparators
    patternFieldEq <- "(?<!selected\\()\\$\\{([^\\}]+)(\\})[:space:]*([=|!|>|<]=*)[:space:]*"
    newRelevant <- stri_replace_all_regex(newRelevant, patternFieldEq, "death\\$$1 $3 ")
 
    # translate or replace " or " with " | "
    newRelevant <- stri_replace_all_regex(newRelevant, " or ", " | ")
    newRelevant <- stri_replace_all_regex(newRelevant, "\\)or", ") | (")
    newRelevant <- stri_replace_all_regex(newRelevant, "or\\(", ") | (")
    
    # translate and odkForm$relevant[437]
    newRelevant <- stri_replace_all_regex(newRelevant, "[:space:]+and[:space:]+", " & ")
    newRelevant <- stri_replace_all_regex(newRelevant, "\\)and", " & ")
    newRelevant <- stri_replace_all_regex(newRelevant, "and\\(", " & ")

    # translate 'NaN' (note previous conversions with = and with field name)
    ## is.na() == TRUE
    patternFieldEq <- "death\\$([^[:space:][:punct:]]+)[:space:]*==[:space:]*'NaN'"
    newRelevant <- stri_replace_all_regex(newRelevant, patternFieldEq, "is.na(death\\$$1)")
    ## is.na() == FALSE
    patternFieldEq <- "death\\$([^[:space:][:punct:]]+)[:space:]*!=[:space:]*'NaN'"
    newRelevant <- stri_replace_all_regex(newRelevant, patternFieldEq, "!is.na(death\\$$1)")

    # translate string-length(${ageInMonthsByYear}) = 0)) with nchar
    patternFieldEq <- "string-length\\(\\$\\{([^\\}]+)\\}\\)"
    newRelevant <- stri_replace_all_regex(newRelevant, patternFieldEq, "nchar(death\\$$1)")

    # translate count-selected 
    patternFieldEq <- "count-selected\\(\\$\\{([^\\}]+)\\}\\)"
    newRelevant <- stri_replace_all_regex(newRelevant, patternFieldEq, "stri_count_words(death\\$$1)")

    # newRelevant
    # eval(parse(text = paste0("death$", newRelevant)))
    # with(data, eval(parse(text = newRelevant)))

    ## devtools::test_file('../tests/testthat/test-item-response.R')
    return(newRelevant)
}


#' Construct item names that capture the hierarchical of an ODK questionnare.
#'
#' \code{itemHierarchy} map the ODK questionnaire hierarchy (i.e. a replication
#' of the field names generated by ODK Aggregate and used in the CSV export).
#'
#' @param odk_form A data frame containing an ODK form.
#'
#' @details
#' Returns the the same data frame, but with an additional column
#' consisting of the group names each item belongs to.  The group names
#' are separated by ".".
#' 
#' @examples
#' \dontrun{
#' ## Example with 2016 WHO VA instrument version 1.5.1
#' 
#' form_f_name151 <- system.file("forms",
#'                               "WHOVA2016_v1_5_1_XLS_form_for_ODK_survey.csv",
#'                               package = "CrossVA")
#' form151 <- read.csv2(form_f_name151, stringsAsFactors = FALSE)
#' itemGroups <- itemHierarchy(form151)$itemGroups
#' }
#'
#' @importFrom stringi stri_replace_all_regex stri_count_words
#' @export
#'
itemHierarchy <- function (odk_form) {

    skipRow <- odk_form$type == ""
    newForm <- odk_form
    newForm$itemGroups <- ""
    current_name <- ""
    n_groups <- 0

    nNames <- function (itemNames) {
        # return the number of groups in groupNames
        splitNames <- strsplit(itemNames, "\\.")
        allNames <- unlist(splitNames)
        return (length(allNames))
    }

    removeLastName <- function (itemNames) {
        # remove last group name; groups separated by a period
        splitNames <- strsplit(itemNames, "\\.")
        allNames <- unlist(splitNames)
        n <- length(allNames)
        namesToKeep <- unlist(splitNames)[-n]
        return (paste0(namesToKeep, collapse = "."))
        
    }
    
    for (i in 1:length(skipRow)) {

        if (skipRow[i]) next

        if (newForm$type[i] == "begin group" & nNames(current_name) == 0) {
            current_name <- newForm$name[i]
            n_groups <- n_groups + 1
            newForm$itemGroups[i] <- current_name
        } else if (newForm$type[i] == "begin group" & nNames(current_name) > 0) {
            current_name <- paste0(c(current_name, newForm$name[i]), collapse = ".")
            n_groups <- n_groups + 1
            newForm$itemGroups[i] <- current_name
        } else if (newForm$type[i] == "end group") {
            current_name <- removeLastName(current_name)
            n_groups <- n_groups - 1
            next
        } else {
            current_name <- paste0(c(current_name, newForm$name[i]),
                                   collapse = ".")
            newForm$itemGroups[i] <- current_name
            current_name <- removeLastName(current_name)
        }
    }

    ## devtools::test_file('../tests/testthat/test-item-response.R')
    return (newForm)
}

#' Calculate item missingness.
#'
#' \code{itemMissing} 
#'
#' @param odk_data A data frame with ODK data
#' @param odk_form A data frame containing an ODK form.
#' @param id_col A string with column name in odk_data with ID (default is "meta.instanceID")
#'
#' @details
#' List with two data frames Deaths and Items.
#' 
#' @examples
#' \dontrun{
#' ## Example with 2016 WHO VA instrument version 1.5.1
#' 
#' record_f_name151 <- system.file("sample",
#'                                 "who151_odk_export.csv",
#'                                 package = "CrossVA")
#' records151 <- read.csv(record_f_name151, stringsAsFactors = FALSE)
#'
#' 
#' form_f_name151 <- system.file("forms",
#'                               "WHOVA2016_v1_5_1_XLS_form_for_ODK_survey.csv",
#'                               package = "CrossVA")
#' form151 <- read.csv2(form_f_name151, stringsAsFactors = FALSE)
#' results <- itemMissing(records151, form151)
#' }
#'
#' @export
#'
itemMissing <- function(odk_data, odk_form, id_col = "meta.instanceID") {

    ## record_f_name151 <- system.file("sample",
    ##                                 "who151_odk_export.csv",
    ##                                 package = "CrossVA")
    ## records151 <- read.csv(record_f_name151, stringsAsFactors = FALSE)

    ## form_f_name151 <- system.file("forms",
    ##                               "WHOVA2016_v1_5_1_XLS_form_for_ODK_survey.csv",
    ##                               package = "CrossVA")
    ## form151 <- read.csv2(form_f_name151, stringsAsFactors = FALSE)
    ## odk_data <- records151
    ## odk_form <- form151
    ## id_col = "meta.instanceID"

    ## set up input data
    split_names <- strsplit(names(odk_data), "\\.")
    death_fnames <- unlist(lapply(split_names, function (x) x[length(x)]))

    ## set up output data
    n_deaths <- nrow(odk)
    index_ID <- which(stri_endswith_fixed(names(odk_data), id_col))
    if (length(index_ID)) {
        DEATHS <- data.frame(ID = odk_data[, index_ID],
                             n_items <- rep(NA, n_deaths),
                             n_ref <- rep(NA, n_deaths),
                             n_dk <- rep(NA, n_deaths),
                             n_miss <- rep(NA, n_deaths))
    } else {
        ## message("Did not find id_col, so assigning row numbers for IDs.",
        ##         call. = FALSE)
        DEATHS <- data.frame(ID = 1:n_deaths,
                             n_items <- rep(NA, n_deaths),
                             n_ref <- rep(NA, n_deaths),
                             n_dk <- rep(NA, n_deaths),
                             n_miss <- rep(NA, n_deaths))
    }

    clean_form <- odk_form[odk_form$name != "",]
    ITEMS <- clean_form[, c('type', 'name', 'relevant', 'required')]
    ITEMS$n_asked <- rep(NA, nrow(clean_form))
    ITEMS$n_ref <- rep(NA, nrow(clean_form))
    ITEMS$n_dk <- rep(NA, nrow(clean_form))
    ITEMS$n_miss <- rep(NA, nrow(clean_form))
    dim(ITEMS)

    ## warning message about which fields are in data, but not in form
    ## and vice versa.

    ## fill in data
    for (i in 1:n_deaths) {
        
        ## i=1
        ## death_fnames[i] %in% clean_form$name
        ## i=2
        ## death_fnames[i] %in% clean_form$name
        ## form151$name[which(clean_form151$name == deathFNames[i])]
        index_form <- which(clean_form$name == deathFNames[i])
        if (length(index_form) == 0) next

        
        if (clean_form$relevant[index_form] == "") {

            ## simple tally
        } else {
            
            i_relevant <- translate(clean_form$relevant[index_form],
                                    odk_data[i,])
        }
    }

    # That's all folks!
    results <- list(Deaths <- DEATHS,
                    Items <- ITEMS)
    return (results)

}
