#' Translate ODK relevant field
#'
#' \code{translate} converts conditions in ODK to R.
#'
#' @param relevant A string from ODK$relevant that needs to be translated.
#'
#' @details
#' This is a worker function.
#' 
#' @examples
#' \dontrun{
#' ## Example with 2016 WHO VA instrument version 1.5.1
#' record_f_name151 <- system.file("sample",
#'                                 "who151_odk_export.csv",
#'                                 package = "CrossVA")
#' records151 <- read.csv(record_f_name151, stringsAsFactors = FALSE)
#' 
#' form_f_name151 <- system.file("forms",
#'                               "WHOVA2016_v1_5_1_XLS_form_for_ODK_survey.csv",
#'                               package = "CrossVA")
#' form151 <- read.csv2(form_f_name151, stringsAsFactors = FALSE)
#' death <- records151[1,]
#' 
#' relevant <- form151$relevant[15]
#' translate(relevant)
#' }
#'
#' @importFrom stringi stri_replace_all_regex stri_count_words
#' @export
#'
translate <- function (relevant) {

    # remove \n
    pattern_selected <- "\n"
    new_relevant <- stri_replace_all_regex(relevant, pattern_selected, " ")

    # replace = with == (but not for >= or <= or !=)
    pattern_selected <- "(?<![>|<|!])="
    new_relevant <- stri_replace_all_regex(new_relevant, pattern_selected, "==")

    # translate selected() -- maybe have separate functions for these
    pattern_selected <- "(?<!not\\()selected\\(\\$\\{([^\\}]+)\\}[^']+('[^']+')\\)"
    new_relevant <- stri_replace_all_regex(new_relevant, pattern_selected, "death\\$$1 == $2")

    # translate not(selected())
    pattern_not_selected <- "not\\(selected\\(\\$\\{([^\\}]+)\\}[^']+('[^']+')\\)\\)"
    new_relevant <- stri_replace_all_regex(new_relevant, pattern_not_selected, "death\\$$1 != $2")

    # translate ${field_name} (separately for !=, =, >, and <)
    # \\1 = field name, \\2 = }, \\3 = relational operator/comparators
    pattern_field_eq <- "(?<!selected\\()\\$\\{([^\\}]+)(\\})[:space:]*([=|!|>|<]=*)[:space:]*"
    new_relevant <- stri_replace_all_regex(new_relevant, pattern_field_eq, "death\\$$1 $3 ")
 
    # translate or replace " or " with " | "
    new_relevant <- stri_replace_all_regex(new_relevant, " or ", " | ")
    new_relevant <- stri_replace_all_regex(new_relevant, "\\)or", ") | (")
    new_relevant <- stri_replace_all_regex(new_relevant, "or\\(", ") | (")
    
    # translate and odkForm$relevant[437]
    new_relevant <- stri_replace_all_regex(new_relevant, "[:space:]+and[:space:]+", " & ")
    ## new_relevant <- stri_replace_all_regex(new_relevant, "\\)and", " & ")
    ## new_relevant <- stri_replace_all_regex(new_relevant, "and\\(", " & ")
    new_relevant <- stri_replace_all_regex(new_relevant, "([:punct:])and", "$1 &")
    new_relevant <- stri_replace_all_regex(new_relevant, "and([:punct:])", "& $1")

    # translate 'NaN' (note previous conversions with = and with field name)
    ## is.na() == TRUE
    pattern_field_eq <- "death\\$([^[:space:][:punct:]]+)[:space:]*==[:space:]*'NaN'"
    new_relevant <- stri_replace_all_regex(new_relevant, pattern_field_eq, "is.na(death\\$$1)")
    ## is.na() == FALSE
    pattern_field_neq <- "death\\$([^[:space:][:punct:]]+)[:space:]*!=[:space:]*'NaN'"
    new_relevant <- stri_replace_all_regex(new_relevant, pattern_field_neq, "!is.na(death\\$$1)")

    # translate string-length(${ageInMonthsByYear}) = 0)) with nchar
    pattern_field <- "string-length\\(\\$\\{([^\\}]+)\\}\\)"
    new_relevant <- stri_replace_all_regex(new_relevant, pattern_field, "nchar(death\\$$1)")

    # translate count-selected 
    pattern_field <- "count-selected\\(\\$\\{([^\\}]+)\\}\\)"
    new_relevant <- stri_replace_all_regex(new_relevant, pattern_field, "stri_count_words(death\\$$1)")

    ## devtools::test_file('../tests/testthat/test-item-response.R')
    return(new_relevant)
}


#' Construct item names that capture the hierarchical of an ODK questionnare.
#'
#' \code{itemHierarchy} map the ODK questionnaire hierarchy (i.e. a replication
#' of the field names generated by ODK Aggregate and used in the CSV export).
#'
#' @param odk_form A data frame containing an ODK form.
#'
#' @details
#' Returns the the same data frame, but with an additional column
#' consisting of the group names each item belongs to.  The group names
#' are separated by ".".
#' 
#' @examples
#' \dontrun{
#' ## Example with 2016 WHO VA instrument version 1.5.1
#' 
#' form_f_name151 <- system.file("forms",
#'                               "WHOVA2016_v1_5_1_XLS_form_for_ODK_survey.csv",
#'                               package = "CrossVA")
#' form151 <- read.csv2(form_f_name151, stringsAsFactors = FALSE)
#' item_groups <- itemHierarchy(form151)$item_groups
#' }
#'
#' @importFrom stringi stri_replace_all_regex stri_count_words
#' @export
#'
itemHierarchy <- function (odk_form) {

    skip_row <- odk_form$type == ""
    new_form <- odk_form
    new_form$item_groups <- ""
    current_name <- ""
    n_groups <- 0

    nNames <- function (item_names) {
        # return the number of groups in groupNames
        split_names <- strsplit(item_names, "\\.")
        all_names <- unlist(split_names)
        return (length(all_names))
    }

    removeLastName <- function (item_names) {
        # remove last group name; groups separated by a period
        split_names <- strsplit(item_names, "\\.")
        all_names <- unlist(split_names)
        n <- length(all_names)
        names_to_keep <- unlist(split_names)[-n]
        return (paste0(names_to_keep, collapse = "."))
    }
    
    for (i in 1:length(skip_row)) {

        if (skip_row[i]) next

        if (new_form$type[i] == "begin group" & nNames(current_name) == 0) {
            current_name <- new_form$name[i]
            n_groups <- n_groups + 1
            new_form$item_groups[i] <- current_name
        } else if (new_form$type[i] == "begin group" & nNames(current_name) > 0) {
            current_name <- paste0(c(current_name, new_form$name[i]), collapse = ".")
            n_groups <- n_groups + 1
            new_form$item_groups[i] <- current_name
        } else if (new_form$type[i] == "end group") {
            current_name <- removeLastName(current_name)
            n_groups <- n_groups - 1
            next
        } else {
            current_name <- paste0(c(current_name, new_form$name[i]),
                                   collapse = ".")
            new_form$item_groups[i] <- current_name
            current_name <- removeLastName(current_name)
        }
    }

    ## devtools::test_file('../tests/testthat/test-item-response.R')
    return (new_form)
}

#' Calculate item missingness.
#'
#' \code{itemMissing} 
#'
#' @param odk_data A data frame with ODK data
#' @param odk_form A data frame containing an ODK form.
#' @param id_col A string with column name in odk_data with ID (default is "meta.instanceID")
#'
#' @details
#' List with two data frames Deaths and Items.
#' 
#' @examples
#' \dontrun{
#' ## Example with 2016 WHO VA instrument version 1.5.1
#' 
#' record_f_name151 <- system.file("sample",
#'                                 "who151_odk_export.csv",
#'                                 package = "CrossVA")
#' records151 <- read.csv(record_f_name151, stringsAsFactors = FALSE)
#'
#' 
#' form_f_name151 <- system.file("forms",
#'                               "WHOVA2016_v1_5_1_XLS_form_for_ODK_survey.csv",
#'                               package = "CrossVA")
#' form151 <- read.csv2(form_f_name151, stringsAsFactors = FALSE)
#' results <- itemMissing(records151, form151)
#' }
#'
#' @export
#'
itemMissing <- function(odk_data, odk_form, id_col = "meta.instanceID") {

    ## record_f_name151 <- system.file("sample",
    ##                                 "who151_odk_export.csv",
    ##                                 package = "CrossVA")
    ## records151 <- read.csv(record_f_name151, stringsAsFactors = FALSE)

    ## form_f_name151 <- system.file("forms",
    ##                               "WHOVA2016_v1_5_1_XLS_form_for_ODK_survey.csv",
    ##                               package = "CrossVA")
    ## form151 <- read.csv2(form_f_name151, stringsAsFactors = FALSE)
    ## odk_data <- records151
    ## odk_form <- form151
    ## id_col = "meta.instanceID"

    ## set up input data
    split_names <- strsplit(names(odk_data), "\\.")
    death_fnames <- unlist(lapply(split_names, function (x) x[length(x)]))
    ## names(odk_data) <- death_fnames
    new_odk_form <- itemHierarchy(odk_form)
    clean_form <- new_odk_form[new_odk_form$name != "",]

    ## set up output data
    n_deaths <- nrow(odk_data)
    index_ID <- which(stri_endswith_fixed(names(odk_data), id_col))
    if (length(index_ID)) {
        DEATHS <- data.frame(ID = odk_data[, index_ID],
                             n_items = rep(0, n_deaths),
                             n_ref = rep(0, n_deaths),
                             n_dk = rep(0, n_deaths),
                             n_miss = rep(0, n_deaths),
                             stringsAsFactors = FALSE)
    } else {
        ## message("Did not find id_col, so assigning row numbers for IDs.",
        ##         call. = FALSE)
        DEATHS <- data.frame(ID = 1:n_deaths,
                             n_items = rep(0, n_deaths),
                             n_ref = rep(0, n_deaths),
                             n_dk = rep(0, n_deaths),
                             n_miss = rep(0, n_deaths))
    }

    ITEMS <- clean_form[, c('type', 'name', 'label..English', 'relevant', 'required')]
    ITEMS$n_asked <- rep(0, nrow(clean_form))
    ITEMS$n_ref <- rep(0, nrow(clean_form))
    ITEMS$n_dk <- rep(0, nrow(clean_form))
    ITEMS$n_miss <- rep(0, nrow(clean_form))

    ## warning message about which fields are in data, but not in form
    ## and vice versa.

    names(odk_data) <- death_fnames
    odk_data$item_response_ID <- DEATHS$ID
    for (i in 1:ncol(odk_data)) {

        index_form <- which(clean_form$name == death_fnames[i])

        if (length(index_form) == 0) next
        
        depends <- strsplit(clean_form$item_group[index_form], "\\.")
        depends <- unlist(depends)
        index_depends <- which(clean_form$name %in% depends)
        depends_relevant <- clean_form$relevant[index_depends]
        if (all(depends_relevant == "")) {
            responses <- odk_data
        } else {
            translated_relevant <- vapply(depends_relevant, translate,
                                          FUN.VALUE = character(1),
                                          USE.NAMES = FALSE)
            translated_relevant <- translated_relevant[!(translated_relevant == "")]
            combined_relevant <- paste0("(", translated_relevant, ")", collapse = " & ")
            combined_relevant <- gsub("death\\$", "odk_data\\$", combined_relevant)
            responses <- eval(parse(text = paste0("subset(odk_data,", combined_relevant, ")")))
        }

        # fill in DEATHS
        ## need to check for missing values for integer types (e.g., 99 = don't know, 98 = refuse)
        ## create a new function for this that goes through integer types and searchs the
        ## constraint (hint as well?)
        DEATHS_index <- match(responses$item_response_ID, DEATHS$ID)
        if (is.charachter(responses[, death_fnames[i]])) {
            DEATHS[DEATHS_index, "n_items"] <- DEATHS[DEATHS_index, "n_items"] + 1
            DEATHS[DEATHS_index, "n_ref"] <- DEATHS[DEATHS_index, "n_ref"] +
                as.numeric(tolower(responses[, death_fnames[i]]) == "ref")
            DEATHS[DEATHS_index, "n_dk"] <- DEATHS[DEATHS_index, "n_dk"] +
                as.numeric(tolower(responses[, death_fnames[i]]) == "dk")
            DEATHS[DEATHS_index, "n_miss"] <- DEATHS[DEATHS_index, "n_miss"] +
                as.numeric(
                    tolower(responses[, death_fnames[i]]) == "" |
                    is.na(responses[, death_fnames[i]])
                )
        }
        ## for numeric (skip calculate?); for integer, looks like they are almost all 99 for don't know
        ## and 88 for refused.  Birth weight uses 9999 and 8888.
        # fill in ITEMS
        if (is.charachter(responses[, death_fnames[i]])) {
            ITEMS[index_form, "n_asked"] <- ITEMS[index_form, "n_asked"] +
                nrow(responses)
            ITEMS[index_form, "n_ref"] <- ITEMS[index_form, "n_ref"] +
                sum(tolower(responses[, death_fnames[i]]) == "ref")
            ITEMS[index_form, "n_dk"] <- ITEMS[index_form, "n_dk"] +
                sum(tolower(responses[, death_fnames[i]]) == "dk")
            ITEMS[index_form, "n_miss"] <- ITEMS[index_form, "n_miss"] +
                sum(tolower(responses[, death_fnames[i]]) == "" |
                    is.na(responses[, death_fnames[i]]))
        }
    }

    ## devtools::test_file("../tests/testthat/test-item-response.R")
    # That's all folks!
    results <- list(Deaths = DEATHS,
                    Items = ITEMS)
    return (results)
}
